name: explorer_example
description: Demonstrates how to use the explorer plugin.
version: 1.0.0+1
publish_to: 'none' 
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  explorer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
